moviepro/movieproject/movieapp/urls.py
from django.urls import path,include
from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

moviepro/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviepro/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=50)
    description=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

moviepro/movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class Mform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','description','year']

moviepro/movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from .models import Movie
from .forms import Mform

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        description = request.POST.get('description',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,description=description,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=Mform(request.POST or None,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

moviepro/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name">
    <input type="text" name="description" placeholder="Enter description">
    <input type="text" name="year" placeholder="Enter movie release year">
    <input type="file" name="img">
    <input type="submit">

</form>
{% endblock %}

moviepro/movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ONLINE MOVIE SPACE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>


      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

moviepro/movieproject/templates/delete.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    do you want to delete this movie?
    <input type="submit">
</form>

moviepro/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="100px" height="200px">
        </div>
    </div>
</div>
<div class="col-md-6">
    <h3>{{movie.name}}</h3>
    <h6>{{movie.description}}</h6>
    <h6>{{movie.year}}</h6>
     <a class="btn btn-warning" href ="{% url 'movieapp:update' movie.id %}">UPDATE</a>
     <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
</div>
</div>
</div>
{% endblock %}

moviepro/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

moviepro/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container"><br>
     <div class="row">
         {% for i in movie_list %}
      <div class="col-lg-4 mb-4">
          <div class="card" style="width: 18rem;">
          <img src="{{i.img.url}}" class="card-img-top" alt="..." width="100px" height="250px">
          <div class="card-body"><br>
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">{{i.description}}</p>
          <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">DETAILS</a><br>
              <br>
          <a href ="{% url 'movieapp:add_movie' %}" a class="btn btn-danger" >ADD</a>
</div>
</div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}